### ISSUE TITLE
make errors: FORTRAN name mangling

### ISSUE THREAD

**Issue by asedova** [TinkerTools/tinker9#129]
Hi, I am trying to build tinker9, and the cmake seems to work fine. The make returns the following error: 
#error directive: We do not know what Fortran compiler you used to
          compile the Tinker  library. You should implement these two macros
          (TINKER_MOD and TINKER_RT) here to mimic its name mangling.
1 catastrophic error detected in the compilation of "/ccs/home/adaa/TINKER/tinker9/src-acc/eangle_acc.cpp".

This happens for all of the cpp files. The Fortran compiler variable is set (FC).

**Comment by zhi-wang** [comment]
What did you set FC to?

I think both GNU and intel Fortran compilers will work. PGI Fortran compiler is a known issue that we can't easily hack up the object files compiled from the Fortran Tinker8 module source code. Even with the standard iso_c binding mechanism, the PGI Fortran had (maybe still has) a bug that will cause a linking error. I'll update the status of PGI Fortran compiler later.

**Comment by asedova** [comment]
FC is set to the pgi compiler
[adaa@login5.summit tinker9]$ echo $FC
/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/pgi-19.9-6rlh73dtf3lmbm6v7r3fkh7tnbeq53hc/linuxpower/19.9/bin/pgfortran

**Comment by zhi-wang** [comment]
Tinker9 is frequently built and tested with gfortran and was tested with ifort in the past. I don't think the code will compile with other Fortran compilers: PGI, oracle, ibm, etc. I have tested PGI in the past and fixing the problem in PGI will take a lot of work. I don't have access to other Fortran compilers so they definitely won't work now, but the fix could be very easy. If you are interested and willing to give it a try, I'll explain it in a follow-up post.

Note that the CPU code in Tinker9 is still serial now and the GPU code can only utilize one GPU card in the node. There is no advantage of using Tinker9 to run CPU code. I'll use Tinker8 instead. Our collaborators have also released Tinker-HP that has MPI.

If you are able to build Tinker9, you are welcome to share with your building toolchains and environment here:

https://github.com/TinkerTools/tinker9/discussions/121

Thanks.

**Comment by zhi-wang** [comment]
The problem with PGI Fortran compiler was discussed here, almost two years ago.

https://forums.developer.nvidia.com/t/136097

**Comment by asedova** [comment]
Ok, thanks. I am hoping to run one replica per GPU card. I will try with FC set to gnu compiler (we don't have intel since this is an IBM system). We are excited about the GPU port!

**Comment by zhi-wang** [comment]
Hi, since we haven't had the chance to test this code base on IBM machines, please let us know if you have any other questions.

**Comment by asedova** [comment]
Thanks so much! Everything seems to have built ok now. Now to run the tests...

**Comment by zhi-wang** [comment]
You are welcome! And we'd really appreciate if you can share your building tool-chains and environment with us here: https://github.com/TinkerTools/tinker9/discussions/121

**Comment by asedova** [comment]
will do... still need to work out how to get the code to find all the gfortran shared libraries since I built with pgi module and FC set to gfortran... looks like my building work is not done...

**Comment by zhi-wang** [comment]
Okay... It took me a lot of effort to make the (cross) linking work on our machines. The basic idea is that cmake will pass the gfortran shared libraries to "pgc++" or "nvc++" (if you are using the re-branded release) via
`CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES` and `CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES` variables.

**Comment by asedova** [comment]
Ok. Could be useful to maybe add this as a cmake flag for future users?  Some way to pass the path to the shared libraries? Or maybe it would be easier to fix the pgifortran issues? Ha ha. I am willing to work on the latter.

**Comment by zhi-wang** [comment]
Sorry that I don't fully understand your request here, but I guess a quick and dirty workaround is to modify these lines:

https://github.com/TinkerTools/tinker9/blob/27f65ba7c5ae932c515e606cadd53828a0b2b8b6/cmake/device.cmake#L57-L58
https://github.com/TinkerTools/tinker9/blob/27f65ba7c5ae932c515e606cadd53828a0b2b8b6/cmake/device.cmake#L94-L95

to include `-LDIRs` and '-lSHAREDs` you needed. I'll see what I can do to make the fix more general.

I was just discussing the pgifortran issue with @jayponder this afternoon. It seemed that the current 20.11 version still hasn't fixed the iso_c_binding bug. There's isn't really much we can do about it before they fix this bug.

**Comment by asedova** [comment]
seems to work-- gets past the library error. I fail the second test however, reading the xyz. I wonder if this is the c++11 problem? This was using gcc 4.8.5.

**Comment by zhi-wang** [comment]
Can you copy your "make test" output here? This problem should be relatively easy to fix. I am using the Tinker8 Fortran subroutines to parse the xyz/parameter files. This error is from the Fortran Tinker and related to the file I/O.

**Comment by asedova** [comment]
[adaa@login5.summit build]$ make test
[  1%] Built target tinker9_f
[  6%] Built target src-libtinker
[  6%] Performing build step for 'src-acc'
[100%] Built target tinker9_acc
[  7%] Performing install step for 'src-acc'
[100%] Built target tinker9_acc
Install the project...
-- Install configuration: "Release"
[  7%] Completed 'src-acc'
[ 10%] Built target src-acc
[ 33%] Built target __t9_all_tests_o
[ 49%] Built target tinker9_cu
[ 97%] Built target __t9_cpp_o
[ 98%] Built target __t9_version_related_o
[100%] Built target tinker9_cpp
[100%] Built target all.tests
Filters: info
 Primary GPU package :  CUDA

 GPU Device :  Setting Device ID to 0 from GPU utilization

 Program Information

    Version:                             1.0.0 GIT 27f65ba
    Synchronized with Tinker commit:     6a1c6104
    C++ compiler:                        pgc++ 19.9.0
    Size of real (bytes):                8
    Size of mixed (bytes):               8
    Using deterministic force:           false
    Debug mode:                          off
    Platform:                            CUDA and OpenACC
    Primary GPU package:                 CUDA
    Latest CUDA supported by driver:     10.1
    CUDA runtime version:                10.1
    Thrust version:                      1.9.6 patch 0
    CUDA compiler:                       nvcc 10.1.243
    OpenACC compiler:                    pgc++ 19.9.0
   GPU detected:                        1
    GPU 0:                              
       PCI:                              0035:04:00.0
       Name:                             Tesla V100-SXM2-16GB
       Maximum compute capability:       7.0
       Single double perf. ratio:        2
       Compute mode:                     exclusive process
       Error-correcting code (ECC):      on
       Clock rate (kHz):                 1530000
       Number of Multiprocessors:        80
       Number of CUDA cores:             5120
       Used/Total GPU memory:            2.08 % / 15.75 GB
===============================================================================
test cases: 1 | 1 passed
assertions: - none -

Filters: [ff],[util]

     ###############################################################    
   ###################################################################  
  ###                                                               ### 
 ###        Tinker9  ---  Software Tools for Molecular Design        ###
 ##                                                                   ##
 ##                    Version 1.0.0-rc   Jan 2021                    ##
 ###                       All Rights Reserved                       ###
  ###                                                               ### 
   ###################################################################  
     ###############################################################    
 Compiled at:  16:05:32  Feb  1 2021
 Commit Date:  Sun Jan 31 10:22:33 2021 -0600
 Commit:       27f65ba


 READXYZ  --  Error in Coordinate File at Atom        0

 Tinker is Unable to Continue; Terminating the Current Calculation

**Comment by asedova** [comment]
same error when running ./tinker9 minimize and then giving it any xyz file

**Comment by zhi-wang** [comment]
This is a new issue to me. I assume if you `cd example` and run `../build/tinker9 analyze dhfr2.xyz e`, you'll see the same error. Theis error happens in the Fortran subroutine that parses the coordinate file. I need to include @jayponder in this discussion now.

**Comment by asedova** [comment]
yes same error:
 ################################################################
 Joint Amber-CHARMM Benchmark on Dihydrofolate Reductase in Water
 23558 Atoms, 62.23 Ang Cube, 9 Ang Nonbond Cutoffs, 64x64x64 PME
 ################################################################

 READXYZ  --  Error in Coordinate File at Atom        0

 Tinker is Unable to Continue; Terminating the Current Calculation

**Comment by zhi-wang** [comment]
I've let @jayponder know this problem and he'll check it shortly. I believe it's a problem with the Fortran code/compiler, and he's far more experienced with these issues than I am.

I assume your gfortran and g++ are both 4.8.5.

Another thing I noticed (which should be irrelevant to the bug you saw) is that you compiled a double precision GPU executable. This should be fine with V100 cards. I am curious to see the performance ratio with respect to the "mixed" precision GPU executable (which is the model that I optimized) on V100. The difference should not be very dramatic for these high-end professional cards.

**Comment by asedova** [comment]
yes, I didn't worry about the prec details for now, just trying to get the build to work and get the build flags figured out. And yes-- this is still with 4.8.5-- I will try with the other version with an updated gcc.

**Comment by zhi-wang** [comment]
I am reading the Fortran source code now. I felt this was a very generic error message. The executable was able to open the xyz file but unable to parse it. I wonder if the canonical Tinker executable has the same problem.

I'd `cd tinker9/tinker/source; cp ../make/Makefile .` Update the FFTW location (around line 50). Delete the Tinker Apple MacOS flags (around line 90) and uncomment the generic linux flags (around line 70). Feel free to remove any fancy flags. Then run `make`. It will compile executables end with `.x` filename extension.

Will you see the same error if you run `/path/to/analyze.x dhfr2.xyz e` ? If you only see this problem in Tinker9, my feeling is some gfortran runtime libraries (for file I/O) are not linked correctly with tinker9.

**Comment by asedova** [comment]
yep that works fine. I must need to add more paths to linked libraries.

**Comment by zhi-wang** [comment]
Just FYI, these are the gfortran flags on my machine. `-L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/x86_64-linux-gnu -L/usr/lib -L/lib/x86_64-linux-gnu -L/lib -lgfortran -lm -lgcc_s -lgcc -lquadmath -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc`

You can `rm tinker9; VERBOSE=1 make tinker9`. You'll see your flags at the end of the output.

**Comment by jayponder** [comment]
I think the Fortran file parsing code is probably correct- lots of people have been using it for a long time. The error you are seeing is happening upon trying to process the very first line of the *.xyz file, the line with the number of atoms in the system and the title string. The error occurs because the first item on this first line of the file as unable to be parsed as an integer (ie, the number of atoms). This is pretty basic and should definitely not occur.

We have an old CentOS 5.11 Linux virtual machine around that uses the GNU 4.9.2 compilers. I seem to remember that this is the oldest version of the GNU compilers that "worked correctly" in building Tinker. So my first suggestion is to update the GNU compilers on the machine where you are building, if you can. The GNU 4.8.5 compilers are from June 2015, and the current stable version is GNU 10.2.

As you and Zhi have already discussed above, I guess it is also possible that you are still missing some library, or perhaps have a mismatch of library versions that are being used.

**Comment by asedova** [comment]
@jayponder the fortran compiler I am using is GNU 7.4.0. Because of the need to use pgi and GNU (due to the pgi iso_c bindings bug) it is tricky on a system with modules to get all the linking right. I am setting FC to gfortran, with the path to that version, but the module environment that is loaded with the pgi module is preventing all of the correct gfortran libraries to be passed in to cmake.

**Comment by zhi-wang** [comment]
Are you able to setup your local PGI config file and put it in your bashrc file, like I suggested in the documentation? Did it work?

**Comment by asedova** [comment]
my flags with verbose are much longer (due partially to spack's naming) but basically I have: -lgfortran -lm -lgcc_s -lgcc -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc 

I haven't tried the local config yet. I did try to load a special module they made to allow pgi c++14, but it doesn't work for me (it's supposed to be their local config solution). I can try it, but I am not sure how an updated GNU for the C++ compiler would affect this, since it seems to be the FORTRAN part? But I can try the local rc fix from your install hints.

**Comment by asedova** [comment]
I am missing quadmath it seems?

**Comment by zhi-wang** [comment]
Please try this local config trick. Once you are sure your g++ and gfrotran versions are the same and PGI compiler is configured to the identical version, please wipe out your build directory and start over from configuring cmake.

I have no idea why you don't see quadmath and I don't know if it's normal or not. I'd worry about this issue later once we straighten out the compiler versions.

**Comment by zhi-wang** [comment]
> I can try it, but I am not sure how an updated GNU for the C++ compiler would affect this, since it seems to be the FORTRAN part?

We use `pgc++` or `nvc++` as executable linker. If your `pgc++` is configured to 4.8.5, it'll attempt to link tinker9 against 4.8.5 gfortran runtime. Whereas if you set your FC to gfortran 7.4.0, all of the Fortran code (including file I/O) is not compatible with the 4.8.5 runtime.

**Comment by asedova** [comment]
How to check that the local rc config has actually been set after the PGI_LOCALRC=/path/to/new_config has been set?

**Comment by zhi-wang** [comment]
This is a good question. I'd first logout to make sure this environmental variable will take effect after I login again. My personal experience is you will no longer see "Your default GNU version is 4.8 where C++11 is incomplete" warning for `acc.cpp` source files.

**Comment by asedova** [comment]
I can't get your recipe to work; I keep getting makelocalrc errors like: ERROR: unexpected target:gcc-4.8.5 and architecture:ppc64le combination. I tried again with the special localrc module that we have (supposed to config with gcc 6.4.0) and setting PGI_LOCALRC=/sw/summit/pgi/cxx14_localrc  (the admin tells me this should work) but I still get the "Your default GNU version is 4.8 where C++11 is incomplete" warning.

**Comment by zhi-wang** [comment]
How does it take to apply for an account on summit? I'd like to take a look myself.

**Comment by asedova** [comment]
I can add you-- send me an email to ada.a.sedova at gmail

**Comment by jayponder** [comment]
I'm closing this, as it appears from other information that the build is not successful.
