### ISSUE TITLE
Tinker9 doesn't support cc86

### ISSUE THREAD

**Issue by leucinw** [TinkerTools/tinker9#132]
This is on RTX-3070 card. `analyze` gives the following error 
`Terminating with uncaught exception :  The code base should be updated for compute capability 86; Please refer to the NVIDIA Cuda-C Programming Guide at gpu_card.cpp:162`

**Comment by zhi-wang** [comment]
Did commit 4dc060d solve this issue?

**Comment by zhi-wang** [comment]
It seems the PGI/NVHPC compiler (20.11) doesn't support the `cc86` compiler flag.

`cc80` works.
