### ISSUE TITLE
string sub-command REPLACE requires at least four arguments

### ISSUE THREAD

**Issue by sergueev** [TinkerTools/tinker9#138]
Hello,
I think I managed to follow all the steps required for the installation setting all the options, compilers, etc. 
However I am stack with the following error:
[ 25%] Performing configure step for 'src-libtinker'
CMake Error at CMakeLists.txt:19 (string):
  string sub-command REPLACE requires at least four arguments.

Sounds like one of the variable is empty thus making it 3 arguments instead of 4 in the replace command.
What am I be missing, what variable I forgot to set ?  Thanks.

**Comment by sergueev** [comment]
I found the lines which causing the problem. The are in the src-libtinker/CMakeLists.txt :
string (REPLACE "\t" "" __T9_LIBTINKER_O ${__T9_LIBTINKER_O})
string (REPLACE "\n" "" __T9_LIBTINKER_O ${__T9_LIBTINKER_O})
string (REPLACE "\r" "" __T9_LIBTINKER_O ${__T9_LIBTINKER_O})
string (REPLACE ".o" ".f" __T9_LIBTINKER_O ${__T9_LIBTINKER_O})
string (REPLACE " \\" ";" __T9_LIBTINKER_O ${__T9_LIBTINKER_O})

**Comment by zhi-wang** [comment]
It seemed that running `git submodule update --init` fixed the problem.

**Comment by zhi-wang** [comment]
More details are explained in this link: https://github.com/TinkerTools/tinker9/discussions/140

**Comment by sergueev** [comment]
Thanks. Indeed, I forgot to do that git submodule update thing. Somehow the installation guide was not so obvious to me and I simply skipped the Canonical part.
