### ISSUE TITLE
NVHPC uses env. var. NVLOCALRC instead of PGI_LOCALRC

### ISSUE THREAD

**Issue by mquevill** [TinkerTools/tinker9#151]
In the docs ( [preq.rst](https://github.com/TinkerTools/tinker9/blob/master/doc/manual/m/install/preq.rst) ), the newer NVHPC compilers read the local rc file via the environment variable `NVLOCALRC`, instead of `PGI_LOCALRC`. Since there was an update for the directory structure of NVHPC, the environment variable for the local rc needs to be updated too.

**Comment by zhi-wang** [comment]
Thanks. I'll fix this in our documentation.

**Comment by zhi-wang** [comment]
Fixed in 288fb673f3b8cd27fd84d24a631ac4ff57152b36
