### ISSUE TITLE
Minimize does not work with neighbor-list

### ISSUE THREAD

**Issue by mquevill** [TinkerTools/tinker9#152]
It seems that `tinker9 minimize` does not work as expected when `neighbor-list` is turned on in the keyfile. I believe in the base version of Tinker, the presence of `neighbor-list` does not affect the minimize routine.

```
$ tinker9 minimize min 0.01 # with GPU, with neighbor-list

 QN Iter     F Value      G RMS      F Move   X Move   Angle  FG Call  Comment

     0   -0.1014D+05 0.4223D+09                                   1
     1   -10175.4329    81.5004     33.0063   0.0008    0.00      3    Success 
     2   -0.1018D+05 0.2883D+08  0.2737D-02   0.0000    0.00     17   IntplnErr
     3   -10175.4328    81.5005     -0.0028   0.0000   87.84     22    Success 
     4   -10175.4331    81.5005      0.0002   0.0000   89.50     28   BadIntpln
     5   -0.1018D+05 0.2883D+08  0.1993D-02   0.0000   84.98     37   BadIntpln

 LBFGS  --  Incomplete Convergence due to BadIntpln
```

```
$ tinker9 minimize min 0.01 # with GPU, no neighbor-list

 QN Iter     F Value      G RMS      F Move   X Move   Angle  FG Call  Comment

     0   -10142.4153    92.7907                                   1
     1   -11955.7576    47.7682   1813.3423   0.0023    0.00      2    Success 
     2   -13836.3307    37.7824   1880.5731   0.0018   24.20      3    Success 
     ...
     ...
     ... # continues as expected
```

**Comment by jayponder** [comment]
In order to debug this efficiently, we will need to see your .xyz file and .key file, as well as your parameter file if its not a standard one distributed with Tinker. Please just make a another post here, and attach the files.

**Comment by zhi-wang** [comment]
Would you upload your files here or send them in an email? wangzhi AT wustl edu

**Comment by mquevill** [comment]
I noticed that the parameter files included in Tinker9 are quite limited, when compared to standard Tinker. Are all the parameter sets from Tinker supported in Tinker9?

I fit these parameters using POLTYPE. The keyfiles and xyz are below (added a .txt suffix to post on GitHub).

[min.key.txt](https://github.com/TinkerTools/tinker9/files/6473364/min.key.txt)
[amoebabio18_header.prm.txt](https://github.com/TinkerTools/tinker9/files/6473375/amoebabio18_header.prm.txt)
[min.xyz.txt](https://github.com/TinkerTools/tinker9/files/6473349/min.xyz.txt)


Without `neighbor-list`:
```
$ tinker9 minimize min 0.01
...
QN Iter     F Value      G RMS      F Move   X Move   Angle  FG Call  Comment

     0    0.6412D+08 0.1121D+07                                   1
     1    0.2778D+08 0.4303D+06  0.3634D+08   0.0034    0.00      2    Success 
     2    0.1731D+08 0.2499D+06  0.1047D+08   0.0021    0.42      3    Success 
     3    0.9465D+07 0.1247D+06  0.7848D+07   0.0029    0.57      4    Success 
     4    0.5455D+07 0.6600D+05  0.4010D+07   0.0029    0.68      5    Success 
     5    0.3094D+07 0.3415D+05  0.2361D+07   0.0033    0.86      6    Success 
     6    0.1812D+07 0.1823D+05  0.1282D+07   0.0034    1.22      7    Success 
     7  1113857.1344 10214.8320 698252.5942   0.0034    2.26      8    Success 
     8   715775.2948  5967.4331 398081.8397   0.0034    3.11      9    Success 
     9   479784.1732  3618.4062 235991.1215   0.0034    4.27     10    Success 
    10   334766.0094  2271.4039 145018.1639   0.0034    5.45     11    Success 
    11   243133.0064  1475.5038  91633.0030   0.0034    7.95     12    Success 
    12   183375.7513   993.1855  59757.2551   0.0034   10.72     13    Success 
    ...
```
With `neighbor-list`:
```
$ tinker9 minimize min 0.01
...
 QN Iter     F Value      G RMS      F Move   X Move   Angle  FG Call  Comment

     0    0.6412D+08 0.6873D+09                                   1
     1    0.6402D+08 0.4318D+08  0.9527D+05   0.0034    0.00      2    Success 
     2    0.6402D+08 0.4318D+08  0.2309D+03   0.0000    3.60      4    Success 
     3    0.6402D+08 0.4318D+08 -0.1561D-03   0.0000   41.01      7    Success 
     4    0.6402D+08 0.4318D+08 -0.4701D-03   0.0000   46.09     13   BadIntpln
     5    0.6402D+08 0.4318D+08 -0.4029D-02   0.0000   68.42     19   BadIntpln

 LBFGS  --  Incomplete Convergence due to BadIntpln
```

**Comment by zhi-wang** [comment]
Thank you for the example. We don't think this is a "bug" related to `neighbor-list`. This keyword caught your attention with the possible underlying issues but it is not the cause of the problem.

Tinker9 uses different code paths: cuda code with neighbor-list keyword and openacc code without neighbor-list keyword. The difference in these code paths is less significant in the energies (F Value of Iter 0) and more significant in the gradients (G RMS). We noticed the VDW energy of this system is very big, indicating the initial structure has a few "bad contacts", which may "magnify" the difference in the gradients using different code paths.

Also, your second example without the `neighbor-list` keyword didn't exit correctly either. It showed that there were other underlying issues related to electrostatics and single-precision floating-point numbers, etc. I think Jay will post his comments on these issues later.

**Comment by ponderlab** [comment]
There are multiple separate issues here:

(1) Polarizable force fields in general are often not robust to poor initial geometries. In this case, your starting structure has some very bad "high energy" contacts. You should first lightly minimize the system without polarization (add keyword "POLARIZETERM NONE"). Then remove this keyword and continue the minimization with polarization.

(2) You are using the "Z-Bisect" local frame on the nitrate O atom. This will not work. You cannot use the Z-Bisect frame whenever the atoms involved can become planar, ie, when the atom having its multipoles defined or the Z-axis attached atom is a trigonal center or can otherwise become planar during a minimization or MD simulation. If POLTYPE used this frame for the nitrate O atom, then this should be changed in POLTYPE.

(3) We already provide pretty good parameters for nitrate anion in the /example directory of the main Fortran Tinker 8 distribution. I would suggest you use these parameters as the AMOEBA model for nitrate.

(4) The issue you are seeing with Tinker9 is not really a "bug", but arises from the use of the Z-Bisect local frame as discussed above. The fact that you get different results with and without the NEIGHBOR-LIST keyword is due to tiny differences in single precision math on the GPU around an instability due to the Z-Bisect frame. The fact that minimization without the keyword works "correctly" is a bit of luck in this case. In well-behaved cases you should indeed get the same result with or without NEIGHBOR-LIST.

**Comment by mquevill** [comment]
(1) I will use a 2-step minimization with polarization off and then on in the future.
(2) I think this was the main issue that I've had, since no matter how far a `minimize` call had gotten, the `dynamic` call would crash after 10-20 steps.
(3) I could not find the nitrate parameters in https://github.com/TinkerTools/tinker/tree/release/example. However, I found the parameters in https://github.com/pren/poltype/issues/30#issuecomment-662025638.
(4) This goes back to (2) since even with a "finished" minimization, the dynamics were very unstable. Using the parameters from (3), I got similar behavior with or without `neighbor-list`.

Thank you all for your help!

**Comment by ponderlab** [comment]
Here are the AMOEBA nitrate parameters that I know to be at least "reasonable":

forcefield              AMOEBA-NITRATE

bond-cubic              -2.55
bond-quartic            3.793125
angle-cubic             -0.014
angle-quartic           0.000056
angle-pentic            -0.0000007
angle-sextic            0.000000022
opbendtype              ALLINGER
opbend-cubic            -0.014
opbend-quartic          0.000056
opbend-pentic           -0.0000007
opbend-sextic           0.000000022
torsionunit             0.5
vdwtype                 BUFFERED-14-7
radiusrule              CUBIC-MEAN
radiustype              R-MIN
radiussize              DIAMETER
epsilonrule             HHG
dielectric              1.0
polarization            MUTUAL
vdw-12-scale            0.0
vdw-13-scale            0.0
vdw-14-scale            1.0
vdw-15-scale            1.0
mpole-12-scale          0.0
mpole-13-scale          0.0
mpole-14-scale          0.4
mpole-15-scale          0.8
polar-12-scale          0.0
polar-13-scale          0.0
polar-14-scale          1.0
polar-15-scale          1.0
polar-12-intra          0.0
polar-13-intra          0.0
polar-14-intra          0.5
polar-15-intra          1.0
direct-11-scale         0.0
direct-12-scale         1.0
direct-13-scale         1.0
direct-14-scale         1.0
mutual-11-scale         1.0
mutual-12-scale         1.0
mutual-13-scale         1.0
mutual-14-scale         1.0

atom          1    1    N     "Nitrate N"     7    14.007    3
atom          2    2    O     "Nitrate O"     8    15.999    1

vdw           1                       3.7100     0.1100
vdw           2                       3.5100     0.1120

bond          1    2                   390.0     1.2606
angle         2    1    2             155.00     120.00
strbnd        2    1    2              18.70      18.70
opbend        2    1    2    2                   172.00

multipole     1    2    2            1.07363
                                     0.00000    0.00000    0.00000
                                     0.14407
                                     0.00000   -0.28814
                                     0.00000    0.00000    0.14407

multipole     2    1    2           -0.69121
                                     0.00000    0.00000    0.04941
                                    -0.50067
                                     0.00000   -0.08271
                                     0.00000    0.00000    0.58338

polarize      1                       1.0730     0.3900      2
polarize      2                       0.8370     0.3900      1
