### ISSUE TITLE
bar program failed in step 2

### ISSUE THREAD

**Issue by leucinw** [TinkerTools/tinker9#153]
Hi @zhi-wang and @jayponder ,

This is to report a failure in free energy simulation using bar of Tinker9. Specifically, this happens in step 2 (get the thermodynamic values) of bar program. The error message it produced is: `Terminating with uncaught exception :  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 2)`
For your convenience, here is the link for all the files of two neighboring windows. 
`https://biomol.bme.utexas.edu/~liuchw/bar_tinker9`

Thanks,
Chengwen

**Comment by zhi-wang** [comment]
The problem is `bar` expects a "title" (same as in the xyz file) on the first line of the bar file.

```
    2000    298.15  Propanol
```

The current `bar` failed to put a safeguard if such a title is an empty string. The quick fix is to add some random words where a title is expected (Line 1 and 2002 in your propanol case).

I'll push the fix later.

**Comment by bdw2292** [comment]
Hello, I just used the version after patching this but I still receive the error
Compiled at:  15:41:14  Jun  1 2021
 Commit Date:  Thu May 27 14:27:38 2021 -0500
 Commit:       727c38b7
 Enter Potential Energy BAR File Name :  /home/bdw2292/Sims/BenzeneSolvation/SolvSim/SolvSimEle0_Vdw0.6/solvwaterboxproddyn.bar
 First & Last Frame and Step Increment for Trajectory A :  1 1000 1
 First & Last Frame and Step Increment for Trajectory B :  1 1000 1
 Terminating with uncaught exception :  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 2)

**Comment by zhi-wang** [comment]
Let me take a look.

**Comment by zhi-wang** [comment]
Can you send me this bar file? On slack maybe?

**Comment by bdw2292** [comment]
This works with new version now, can close :)
