### ISSUE TITLE
Starting frame index not applied in BAR step 2?

### ISSUE THREAD

**Issue by leucinw** [TinkerTools/tinker9#154]
In BAR step 2, my intention is to drop out the initial 500 frames and to use the rest of the frames to calculate free energy. So I used command such as `$TINKER9/build/bar9.sh 2 $filename.bar 500 2000 1 500 2000 1`. However, from the output, I can see that the free energy is estimated with all the frames (2000 here). Does this mean the `starting frame index` is ignored in Tinker9?

**Comment by zhi-wang** [comment]
Thank you for the bug report.

This should be fixed in e5b23cb4b5bbc2de777ce7e4f5e4cd4650042996

BTW, if you intend to ignore the first 500 frames, the frames should read `501 2000 1`.
