### ISSUE TITLE
Gas phase .bar files dont have third column of volume information

### ISSUE THREAD

**Issue by bdw2292** [TinkerTools/tinker9#158]
For solvation, we have gas phase (no box info in arc/key file). A .bar file will generate without third column however when I run bar option 2, this happen

Compiled at:  14:39:01  Jun  8 2021
 Commit Date:  Mon Jun 7 17:16:18 2021 -0500
 Commit:       cdf265c2
 Simulation Trajectory A and Thermodynamic State 0 :
 Title
 Number of Frames :         974
 Temperature :           300.00
 Simulation Trajectory B and Thermodynamic State 1 :
 Title
 Number of Frames :         974
 Temperature :           300.00
 Free Energy Difference via FEP Method :
/home/liuchw/Documents/Github.leucinw/Tinker9/build_1/bar9.sh: line 4: 2421047 Segmentation fault      (core dumped) "${DIR}"/tinker9 bar "$@"

**Comment by bdw2292** [comment]
Perhaps not a big issue we can use bar from tinker CPU version

**Comment by zhi-wang** [comment]
I'll still fix it.

**Comment by zhi-wang** [comment]
Fixed in 67243e342e45aafd5dbf0171e9617de97cdfe308

**Comment by bdw2292** [comment]
Thanks!
