### ISSUE TITLE
Semi-isotropic pressure scaling

### ISSUE THREAD

**Issue by batukav** [TinkerTools/tinker9#181]
Hello All,
Is the semi-isotropic pressure coupling implemented for any of the current barostats?

**Comment by zhi-wang** [comment]
I don't think there is any "semi-isotropic" barostat implemented.

**Comment by batukav** [comment]
Thank you and sorry for this late reply. 

We are planning to use Tinker9 for lipid bilayer simulations. In our experience with other MD softwares, the semi-isotropic pressure coupling is the best option for the lipid bilayers, compared to anisotropic and full-isotropic pressure coupling. 

By semi-isotropic pressure coupling I mean the pressure tensor is coupled in xy-plane and independent from the z-axis. Is there any plan to include such coupling in Tinker9?

**Comment by zhi-wang** [comment]
Dr. @pren just explain it to me. The cell fluctuation in the xy-plane is isotropic and independent from the z-axis. Is this going to be an orthogonal cell or monoclinic and triclinic cells are also possible use cases?

**Comment by ohsOllila** [comment]
We, and probably large majority of other users, would be interested in using orthogonal cell. However, for some applications, such as membrane proteins, there might be interest for other box types to decrease the size of simulation box without reducing the periodic distance between, for example, proteins in membrane.

**Comment by zhi-wang** [comment]
I think I know how to code the semi-isotropic and anisotropic cell fluctuations in Tinker9. It'd also be helpful for me to have some test cases where you know what the average box shape and size at equilibrium are.

**Comment by ohsOllila** [comment]
There are plenty of such examples from lipid bilayers simulated with other programs. Which kind of input file format would be easiest for you? I could send you Gromacs and/or OpenMM input files for a bilayer simulation for which we know the box equilibrium values. @batukav might have such files also for other programs.

**Comment by zhi-wang** [comment]
I haven't handled a lot of format conversion in the past so please let me ask Prof. @jayponder 's opinion first. Thank you in advance.

**Comment by zhi-wang** [comment]
Sorry that I'm still a little confused by one of the early replies, because the term "semi/anisotropic pressure" was used, and I have been referring to the term "anisotropic cell fluctuation."

If what you are looking for is the algorithm to simulate systems under an anisotropic Cauchy Tensor instead of a hydrostatic pressure, I am afraid that it is a lot more complex than it looks and we probably won't have immediate support for it. Semi/anisotropic cell fluctuation under the constant hydrostatic pressure is what we are going to test. I hope this is also what you wanted.

**Comment by ohsOllila** [comment]
With the semi-isotropic coupling we mean that the x/y directions in the pressure tensor are scaled isotropically, i.e. their average pressure is set to the target value, and the z-direction is scaled independently from this. Consequently, the x/y ratio of the box size remains constant but the area is changing with respect to z-direction. Decoupling of x/y direction from z-direction is necessary for simulations of interfaces at equilibrium tension. Here is the link to the description of this in Gromacs: https://manual.gromacs.org/current/reference-manual/algorithms/molecular-dynamics.html#pressure-coupling

In principle, bilayers can be also run with fully anisotropic coupling. We have tried this with Tinker and AMOEBA but we will probably need some help there. @batukav is preparing an another issue on those.

**Comment by zhi-wang** [comment]
I get it. I think we are on the same page.

Do you mind if I ask what force field you have used in these applications? (As it is noted in Gromacs' manual that there is a lot of trouble in the systems with holonomic constraints.)

**Comment by ohsOllila** [comment]
We and others have used dozens of different additive force fields to run MD simulations of lipid bilayers with Gromacs. Indeed, bond constraints might make the implementation slightly more complicated. With Tinker we are mainly interested to run AMOEBA. I am not sure now if there are constraints used, but @batukav probably knows this.

**Comment by batukav** [comment]
Hello,

We are mostly interested in running bilayer simulations with AMOEBA. For these systems, I am not aware of any constraints.

I might be mistaken but the aren't holonomic constraints in Gromacs calculated via SETTLE and SHAKE?

**Comment by zhi-wang** [comment]
Hi, would you send us some test cases? We will manage to convert the coordinate and the force field files into the Tinker format. My email is wangzhi@wustl.edu Thanks!

**Comment by ohsOllila** [comment]
For example, this is a standard simulation and could be a good test case:
https://doi.org/10.5281/zenodo.1198158

Area per lipid for that simulation is in here:
https://github.com/NMRLipids/Databank/blob/main/Data/Simulations/90f/90b/90f90b7a9097418bd99f312299cf76f3ca86e403/e6620192a44308917b63dd11a7e7c34c1c8aa131/apl.json

If you find OpenMM input easier, this is also an option:
https://doi.org/10.5281/zenodo.153947

**Comment by blakemertz** [comment]
Zhi, if you haven't gotten any test case files from Batu yet, ping me -- I've got some 128-lipid systems for DMPC and DOPC that are already in the file format to use the Li AMOEBA parameters.

**Comment by zhi-wang** [comment]
@blakemertz! Yes, please! That would be very helpful.

@batukav Yes, I did receive your files and I have forwarded them to Prof. Ponder. We are ready to test the Li AMOEBA parameters in Tinker9 at this point (I think). As for the comparison to the partial charge force field, we are kind of slow and still haven't got the chance to convert the file formats...

**Comment by jayponder** [comment]
Hi, As Zhi says if you have a simple 128-lipid system with water that has the coordinates file typed for the Li AMOEBA lipid parameters, please post it here or send it to us via email.

I guess we also want to run the CHARMM36 test in the link in a message above. That will require converting from Gromacs or OpenMM format. Neither of those should be too difficult but it's kind of time, but I simply haven't found time
