### ISSUE TITLE
T9_ACC_COMPILER

### ISSUE THREAD

**Issue by eneas77** [TinkerTools/tinker9#194]
After proper NVIDIA HPC SDK installation, cmake compilation fails with next message:

cmake -T9_ACC_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/compilers/bin/nvc++ -B /apps/tinker/tinker9/build-cmake -S /apps/tinker/tinker9
CMake Error at CMakeLists.txt:374 (find_program):
  Could not find T9_ACC_COMPILER using the following names: nvc++, pgc++

-- Configuring incomplete, errors occurred!

Any idea of how to properly set the nvc++ env?

Thanks a lot

**Comment by zhi-wang** [comment]
Hi, I didn't create such a flag for setting the ACC compiler. If there is anything in the installation step3 (https://github.com/TinkerTools/tinker9/blob/master/doc/manual/m/install/buildwithcmake.rst) that looks ambiguous to you, please let me know. Thanks.

P.s.,
I'd try the following
```
ACC=... FC=... cmake -B ... -S ...
```

**Comment by eneas77** [comment]
Sorted!! THanks!!
