### ISSUE TITLE
Rebuild application

### ISSUE THREAD

**Issue by eneas77** [TinkerTools/tinker9#195]
Hi,

After compiling tinker9, the next message apperas when running all.tests:

Primary GPU package :  CUDA

 GPU Device :  Setting Device ID to 0 from GPU utilization
Current file:     /apps/tinker/tinker9/src/acc/mdpq.cpp
        function: _ZN6tinker18mdCopyPosToXyz_accEv
        line:     11
This file was compiled: -acc=gpu -gpu=cc60 -gpu=cc70
Rebuild the application with -gpu=cc86 to use NVIDIA Tesla GPU 0
---------------------------------------------------------------
My GPU actual card is a GeFOrce RTX 3060 Ti, which is a Ampere architecture. Is that message related with some rebuilt requirements?

Thank you kindly

**Comment by zhi-wang** [comment]
I'd use `-DCOMPUTE_CAPABILITY=80`

> -DCOMPUTE_CAPABILITY (compute_capability) = 60,70
> GPU code only.
> CUDA compute capability (multiplied by 10) of GPU. Valid values (noninclusive) are 35, 50, 60, 70, 75 etc., and can be comma-separated, e.g. 35,60. Multiple compute capabilites will increase the size of executables.
> The full list of compute capabilities can be found on the [NVIDIA website.](https://developer.nvidia.com/cuda-gpus)

https://github.com/TinkerTools/tinker9/blob/master/doc/manual/m/install/buildwithcmake.rst

**Comment by eneas77** [comment]
it worked nicely! Thank you very much
