### ISSUE TITLE
minimize9 failure

### ISSUE THREAD

**Issue by BJWiley233** [TinkerTools/tinker9#198]
I am running minimize9 on my protein and small molecule complex I made using Poltype2.  Below is input and xyz and key files (using amoebabio18.prm) as well as the error I am getting.

[uncomplexed_comp.xyz](https://drive.google.com/file/d/1J_GNWvGJFXoR9XkGeqWK0pjgPKiAVVXr/view?usp=sharing)
[Ribociclib_Bind_comp_config.key](https://drive.google.com/file/d/1PrpJVxBTiYUsiyg7zlcJ24QPP5kZCVbX/view?usp=sharing)
```
/home/tinker9/bin/gpu-m/minimize9 uncomplexed_comp.xyz -k Ribociclib_Bind_comp_config.key 0.01
```
traceback:
```
Primary GPU package :  CUDA

 GPU Device :  Setting Device ID to 0 from GPU utilization

 Limited Memory BFGS Quasi-Newton Optimization :

 QN Iter     F Value      G RMS      F Move   X Move   Angle  FG Call  Comment

     0    0.2087D+09 0.4823D+06                                   1
     1    0.1812D+09 0.4287D+06  0.2755D+08   0.0115    0.00      3    Success
     2    0.1571D+09 0.3827D+06  0.2411D+08   0.0115   11.01      5    Success
     3    0.1359D+09 0.3416D+06  0.2119D+08   0.0115   14.89      7    Success
     4    0.1172D+09 0.3045D+06  0.1867D+08   0.0115   17.38      9    Success
     5    0.1008D+09 0.2708D+06  0.1645D+08   0.0115   19.15     11    Success
     6    0.8628D+08 0.2401D+06  0.1448D+08   0.0115   20.54     13    Success
     7    0.7357D+08 0.2119D+06  0.1271D+08   0.0115   21.75     15    Success
     8    0.6247D+08 0.1861D+06  0.1110D+08   0.0115   22.91     17    Success
     9    0.5290D+08 0.1636D+06  0.9574D+07   0.0115   25.09     19    Success
    10    0.4454D+08 0.1430D+06  0.8357D+07   0.0115   25.78     21    Success
 Backtrace
    1  /home/tinker9/bin/gpu-m/minimize9                             0x56bb83
    2  /home/tinker9/bin/gpu-m/minimize9                             0x67d447
    3  /home/tinker9/bin/gpu-m/minimize9                             0x54bcb3
    4  /home/tinker9/bin/gpu-m/minimize9                             0x6757a0
    5  /home/tinker9/bin/gpu-m/minimize9                             0x6a2417
    6  /home/tinker9/bin/gpu-m/minimize9                             0x6a2727
    7  /home/tinker9/bin/gpu-m/minimize9                             0x6f03ab
    8  /home/tinker9/bin/gpu-m/minimize9                             0x7305fe
    9  /home/tinker9/bin/gpu-m/minimize9                             0x70a356
   10  /home/tinker9/bin/gpu-m/minimize9                             0x6f1116
   11  /home/tinker9/bin/gpu-m/minimize9                             0x411fc7
   12  /lib/x86_64-linux-gnu/libc.so.6                               __libc_start_main
   13  /home/tinker9/bin/gpu-m/minimize9                             0x410c6a
 Terminating with uncaught exception :  INDUCE  --  Warning, Induced Dipoles are not Converged at /home/tinker9/src/cu/amoeba/pcg.cu:311
```
I don't get any error when running with regular `minimize` but it runs forever.

**Comment by jayponder** [comment]
Hi Brian,  You need to look at the output.. The energy of your starting structure is 2 X 10^9. That's pretty large :)  After the 10 iterations shown in your output, the energy is still huge. I suspect there are some very, very bad contacts in your initial structure, and the minimizer thrashes around and gets to some spot where, in fact, the induced dipoles do not converge as per the error message.

Polarizable force fields are not as "robust" as simple fixed charge force fields. If you give them starting structures that are too poor, they can and will fail. 

One trick to try is to add the keyword "POLARIZETERM NONE" to your keyfile before you start the minimization from your initial poor structure with the huge energy value. You will only want to run some limited number of iterations, just to get rid of bad contacts. Then remove or comment this keyword and continue the minimization with the polarization present again. Sometimes, if you initial structure is really, really bad, you can also add the "MULTIPOLETERM NONE" keyword before initial, crude minimization.

Remember that if you are just doing minimization to clean up your structure prior to starting molecular dynamics, you only need to minimize to an RMS gradient per atom convergence criterion of 1.0 kcal/mol/Ang. In fact a gradient criterion of 3.0 or so is often sufficient. If you ask for very tight convergence (the default is 0.01) with a big protein system, it will take "forever".

**Comment by BJWiley233** [comment]
Thanks Dr. Ponder, makes perfect sense.

Brian

**Comment by BJWiley233** [comment]
Hi Zhi,

Yes, thanks.  I took the advice of Dr. Ponder.  I knew it was pretty high energy but thought it might run anyway :)

Brian
