### ISSUE TITLE
Aromatic rings warped with OPLS-AA

### ISSUE THREAD

**Issue by eneas77** [TinkerTools/tinker9#201]
Hi,

When runnning a minimization invoking Tinker9 minimze with an organic molecule parametrized with OPLS (Ligpargen), I notice aromatic rings warped when the molecule is zwitterionic, like the following one...

![imagen](https://user-images.githubusercontent.com/93999052/176660529-aa3c4759-befe-4f69-ace1-d00fe5053eb2.png)

So the result is this:

![imagen](https://user-images.githubusercontent.com/93999052/176660384-260e3159-c165-4e14-8ec3-11c7a0cdae6d.png)

I´ve checked the .key file, comparing it with other non-zwitterionic molecules, and the parametrisation looks fine. Aromatic atoms are accordingly labelled with CA atom types, torsional values ok, etc. I haven´t escrutinize the file carefully, just a superficial check.

So I´m wondering either this is an artifact of the parametrisation 

or either

an issue of the oplsa-aa force field. I would appreciate any ideas in regards to this.

Thank you kindly,

E77.

**Comment by jayponder** [comment]
LigParGen is kind of out of our hands, as the parameters are from the Jorgensen group. But if you can post the Tinker .xyz and .key files, I'll take a look and see if I can find the issue.

Obviously for minimization of this isolated molecule in the "gas phase", it is trying really, really hard to make a salt bridge. I suspect this molecule might behave fine if you put it into a box of water.

**Comment by eneas77** [comment]
Hi,

Thanks for this. After trying differente FF (OPLS, OPLS2005, MM2, MM3, AMBER, MMFF) all of them reproduce the same warping in gas phase, so is not code related. Definetely is worth to adjust the improper torsion values to get a proper behaviour of these type of zwitterions...

Thank you so much,

E77

**Comment by jayponder** [comment]
As I implied above, this is not surprising. Two comments. First, force fields are an interpolation method and are only "correct" for small deviations around natural structures. If you "adjust the improper torsion values", then these force fields will almost certainly be far too rigid when the interactions are smaller, such as in solution. Second, I would not be surprised if QM calculation on such zwitterions in the gas phase are also significantly deformed..
