### ISSUE TITLE
Solvate command

### ISSUE THREAD

**Issue by eneas77** [TinkerTools/tinker9#202]
Hi,

I´m trying to use the Solvate command to make a gb minimization of my molecule, however, it looks like the enrgy is the same as the gas-phase results... Maybe is not clear for me the proper usage of the solvate KEYWORD, so I would appreciate a quick refresh of it at.

I just add the following line to the .key file:
solvate gb

Is there anything more to add here?

Thank you kindly,

E77

**Comment by jayponder** [comment]
Sorry, I just saw that this was in the Tinker9 (ie, GPU code) discussion. I believe that implicit solvation models are not currently implemented at all in the Tinker9 GPU code. My comments directly above about use of GB and GK models apply only to the CPU version of Tinker (ie, "Tinker8").
