### ISSUE TITLE
Tinker9 compilarion issue

### ISSUE THREAD

**Issue by kostalv** [TinkerTools/tinker9#204]
Hi,

I am trying to compile Tinker9 according to https://github.com/TinkerTools/tinker9/blob/master/doc/manual/m/install/buildwithcmake.rst

I have the NVIDIA GeForce RTX 3080 and gcc 10.4.0, cuda 11.7, openacc of 22.5 and cmake 3.23.2 installed via spack. However, when I run 
$cmake -DCMAKE_Fortran_COMPILER=gfortran -DCOMPUTE_CAPABILITY=86 ..

an error of "The CUDA compiler identification is unknown" occurs. I am not sure if it  is relevant but in the "CMakeError.log" file I see Compiler: /usr/local/cuda/bin/nvcc which seems like cmake did not use my installed nvcc but rather used some default path.

Could you please provide me with some advise? Thanks.

**Comment by zhi-wang** [comment]
I don't recall having seen this error message... I don't think the problem is directly related to Tinker9. Would you take a look at this link regarding cmake? https://gitlab.kitware.com/cmake/cmake/-/issues/21862
