### ISSUE TITLE
dynamic9 prints out `****` at coordinate xyz positions

### ISSUE THREAD

**Issue by BJWiley233** [TinkerTools/tinker9#208]
Hey @zhi-wang,

Have you ever seen dynamic9 print out `****` at coordinate lines of an arc file?  I just got a termination running dynamic9 and seeing this for some of the waters.

```
$ grep 10365 MD_SolvE0-5_V1_solvboxproddyn.282
  5140  H    -19.16182984  -19.71036514  -14.60326999   350  5138
  8261  O    -47.41036595    8.77489055  -15.43932263   349  8262  8263
 10364  O   -865.98811735  890.82117391 1068.58739584   349 10365 10366
 10365  H  59593.51386404****************************   350 10364
 12296  O      7.28099076    2.00178542   -0.51036590   349 12297 12298
 13214  O  10365.68439796****************************   349 13215 13216
 14664  H  57719.12120651**************58218.21036563   350 14663
```

**Comment by zhi-wang** [comment]
There can be a lot of reasons. The top two most likely ones are the bad FF parameters and a glitch in the program. Chances are 80-20 in my experience.

**Comment by BJWiley233** [comment]
Makes sense.  A rerun has completed so tossing it up to HPC issue.  Thanks for the response.
