### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by dmr3** [TinkerTools/tinker9#227]
I compiled Tinker9 on two workstations with 2080ti gpus, one has cuda 11.8 and the other had 11.5. Both went smoothly and the tests all passed.  

However, on our cluster with A5000 gpus, the build appeared to go smoothly, but two tests (summarized below) failed

````
#cloned it and hopped into the tinker9 dir
git submodule update --init
module load cuda/11.8.0
# mkdir and cd into build dir
FC=gfortran compute_capability=80 gpu_lang=cuda ~/cmake-3.26.4-linux-x86_64/bin/cmake ..
make 
make test
````

test synopsis:
````
Angle-Trpcage

---Tinker/tinker9/test/angle.cpp:8: FAILED:
due to unexpected exception with message:
  stoi

NBList-ArBox

---Tinker/tinker9/test/nblist.cpp:148: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
````

summary:

===============================================================================
test cases:    53 |    51 passed | 2 failed
assertions: 29754 | 29752 passed | 2 failed

**Comment by jayponder** [comment]
Not sure what is going on here. We also have an A5000 GPU. It is installed on a machine running Ubuntu 20.04, with CUDA 11.1, the 470.182.03 driver, and the GNU 9.4 compiler suite. Tinker9 builds fine with that configuration, and runs correctly on the A5000 including passing all of "make test".

**Comment by dmr3** [comment]
I messed up the compute_capability parameter (should have been 86). I recompiled and ran the tests and all passed

also just compiled on a cluster of V100 with passing tests.  

Thanks!
