### ISSUE TITLE
Tinker9 Compilation for CC 89

### ISSUE THREAD

**Issue by cdpoon** [TinkerTools/tinker9#229]
We have installed a bunch of servers with L40 GPUs, compute capability 89.  When I compile Tinker9 with cc 89, I got the following error.

nvc++-Error-Switch -ta with unknown keyword cc89
-ta=host|multicore|tesla:{[no]autocollapse|ptxinfo}
                    Choose target accelerator (supported only for OpenACC, DEPRECATED please refer to -acc and -gpu)
    host            Compile for serial execution on the host CPU
    multicore       Compile for parallel execution on the host CPU
    tesla           Compile for parallel execution on a Tesla GPU
     [no]autocollapse
                    Automatically collapse tightly nested parallel loops
     ptxinfo        Print ptxas information
make[2]: *** [src/acc/CMakeFiles/tinker9_acc.dir/build.make:76: src/acc/CMakeFiles/tinker9_acc.dir/amoeba/empoleewald.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:649: src/acc/CMakeFiles/tinker9_acc.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
FATAL:   While performing build: while running engine: exit status 2

Is there a way to fix it?  I am using NVHPC 22-11.  Could that be the problem?

Thanks so much,

CD Poon
University of North Carolina at Chapel Hill

**Comment by zhi-wang** [comment]
It is the problem in the nvcc compiler that cc89 is not supported.
Supported cc values should be easy to find in the online documents.

**Comment by cdpoon** [comment]
I have NVHPC 22-11 installed.  Here is what it says in the nvcc --help command.

        Allowed values for this option:  'compute_35','compute_37','compute_50',
        'compute_52','compute_53','compute_60','compute_61','compute_62','compute_70',
        'compute_72','compute_75','compute_80','compute_86','compute_87','compute_89',
        'compute_90','lto_35','lto_37','lto_50','lto_52','lto_53','lto_60','lto_61',
        'lto_62','lto_70','lto_72','lto_75','lto_80','lto_86','lto_87','lto_89',
        'lto_90','sm_35','sm_37','sm_50','sm_52','sm_53','sm_60','sm_61','sm_62',
        'sm_70','sm_72','sm_75','sm_80','sm_86','sm_87','sm_89','sm_90'.

It looks like compute_89 is supported.

**Comment by zhi-wang** [comment]
I’m sorry. My bad. I meant nvc++, the acc compiler. nvcc is responsible for
the cuda code which is fine.

**Comment by cdpoon** [comment]
I have tried compiling Tinker9 with the latest NVHPC 23.5 and it gives me the same error.  Does it mean we need to wait for future release of the ACC compiler to fix the problem?

**Comment by cdpoon** [comment]
Thanks for the information.  I compiled Tinker9 for cc 70, 80, 86 with NVHPC 22.11 and 23.5 without any problem.  Will try to run in L40 and see.

**Comment by cdpoon** [comment]
Tinker9 compiled with NVHPC for cc 70, 80, 86 seems to be working in L40 GPU cc89.
