### ISSUE TITLE
Same error on every computer after weekend - tinker9 does not work anymore

### ISSUE THREAD

**Issue by AlainWil** [TinkerTools/tinker9#236]
We have this message if we try to run tinker9 on different computers after weekend!
Was running friday on both computers!
Automatic update of what?

Backtrace
    1  ./tinker9                                                     0x179c3d
    2  ./tinker9                                                     0x1a9514
    3  ./tinker9                                                     0x18e6ed
    4  ./tinker9                                                     0x1a2ad8
    5  ./tinker9                                                     0x22903
    6  /lib/x86_64-linux-gnu/libc.so.6                               0x29d90
    7  /lib/x86_64-linux-gnu/libc.so.6                               __libc_start_main
    8  ./tinker9                                                     0x238e5

Whats the possible problem?

**Comment by zhi-wang** [comment]
I wish I could know your computers better than you do. I can't imagine what they went through this weekend :(
